### ISSUE TITLE
MLB GameDay API

### ISSUE THREAD

**Issue by msroth** [benjamincrom/baseball#2]
I know your website says the MLB GameDay API is down, but I think it still exists, you just can't browse the data any longer, you have to construct specific URLs now.  For example:  http://gd2.mlb.com/components/game/mlb/year_2020/month_03/day_09/gid_2020_03_09_detmlb_houmlb_1/boxscore.xml.  I hope you can get your site back online, I really enjoyed it last season.

**Comment by benjamincrom** [comment]
I'm happy to announce that https://livebaseballscorecards.com is back up!
